# Generated by Django 4.2 on 2023-04-05 01:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=48, unique=True)),
                ('message', models.JSONField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('send', 'Send'), ('deferral', 'Deferral'), ('hard_bounce', 'Hard Bounce'), ('soft_bounce', 'Soft Bounce'), ('delivered', 'Delivered'), ('open', 'Open'), ('click', 'Click'), ('spam', 'Spam'), ('unsub', 'Unsub'), ('reject', 'Reject')], max_length=20)),
            ],
        ),
    ]
