# Generated by Django 4.2 on 2023-04-05 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mandrill', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webhookmessage',
            options={'ordering': ['-created_at']},
        ),
    ]
